FileVersion = 1
Projects = {SteelEngine = {Path = "Engine"}, SteelEditor = {Path = "Editor"}, glfw-beef = {Path = "Libs/GLFW"}, imgui-impl-opengl3 = {Path = "Libs/imgui/imgui-impl-opengl3"}, imgui-impl-glfw = {Path = "Libs/imgui/imgui-impl-glfw"}, imgui-beef = {Path = "Libs/imgui/imgui-beef"}, JSON_Beef = {Path = "Libs/JSON_Beef/lib"}, BeefExtensionsLib = {Path = "Libs/Beef-Extensions-Lib"}}
Locked = ["glfw-beef", "imgui-impl-opengl3", "imgui-impl-glfw", "imgui-beef"]

[Workspace]
StartupProject = "SteelEditor"
