FileVersion = 1
Projects = {Engine = {Path = "Engine"}, Editor = {Path = "Editor"}}

[Configs.Test.Win32]
ConfigSelections = {corlib = {Config = "Debug"}}

[Configs.Test.Win64]
ConfigSelections = {corlib = {Config = "Debug"}}
