FileVersion = 1
Dependencies = {corlib = "*", SteelEngine = "*", BeefExtensionsLib = "*", JSON_Beef = "*", ImGui = "*", ImGuiImplGlfw = "*", ImGuiImplOpenGL3 = "*"}

[Project]
Name = "SteelEditor"
StartupObject = "SteelEditor.Program"

[Configs.Debug.Win64]
BeefLibType = "DynamicDebug"
DebugWorkingDirectory = "$(WorkspaceDir)"
