FileVersion = 1
Dependencies = {corlib = "*", SteelEngine = "*", imgui-impl-opengl3 = "*", imgui-impl-glfw = "*", imgui-beef = "*", BeefExtensionsLib = "*", JSON_Beef = "*"}

[Project]
Name = "SteelEditor"
StartupObject = "SteelEditor.Program"

[Configs.Debug.Win64]
BeefLibType = "DynamicDebug"
